---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-demo-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: todo-demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: not-helm
    repoURL: https://github.com/ultraJeff/todo-demo-app-helmrepo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false